---
- name: Update Linux hosts
  hosts: all
  tasks:

  - name: Upgrade Red Hat based machines
    yum:
      name: '*'
      state: latest
      update_cache: yes
    when: ansible_os_family == "RedHat" and not skip_update.defined
